[jellyfin]
src.container = "jellyfin/jellyfin"
fetch.docker = "jellyfin/jellyfin"

[bazarr]
src.container = "linuxserver/bazarr"
src.include_regex = "\\d+\\.\\d+\\.\\d+"
fetch.docker = "linuxserver/bazarr"

[sonarr]
src.container = "linuxserver/sonarr"
src.include_regex = "\\d+\\.\\d+\\.\\d+"
fetch.docker = "linuxserver/sonarr"

[radarr]
src.container = "linuxserver/radarr"
src.include_regex = "\\d+\\.\\d+\\.\\d+"
fetch.docker = "linuxserver/radarr"

[prowlarr]
src.container = "linuxserver/prowlarr"
src.include_regex = "\\d+\\.\\d+\\.\\d+"
fetch.docker = "linuxserver/prowlarr"

[caddy]
src.container = "library/caddy"
src.include_regex = "\\d+\\.\\d+\\.\\d+"
fetch.docker = "library/caddy"

[qbittorrent]
src.container = "linuxserver/qbittorrent"
src.include_regex = "\\d+\\.\\d+\\.\\d+"
fetch.docker = "linuxserver/qbittorrent"

[adguard]
src.container = "adguard/adguardhome"
fetch.docker = "adguard/adguardhome"

[tor-privoxy]
src.container = "dockage/tor-privoxy"
fetch.docker = "dockage/tor-privoxy"

[minecraft-server]
src.container = "itzg/minecraft-server"
src.include_regex = "java8"
fetch.docker = "itzg/minecraft-server"

[odin]
src.container = "mbround18/valheim"
fetch.docker = "mbround18/valheim"
