# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  adguard = {
    pname = "adguard";
    version = "v0.108.0-b.72";
    src = dockerTools.pullImage {
      imageName = "adguard/adguardhome";
      imageDigest = "sha256:85ff4c3e4344d8ac40c0e9dacd15ac79a5eac220f94255ab3066ed67655a5f42";
      sha256 = "sha256-mheJqQTRmT5m0mr4KXU7m+W4jOW3tVNneMuJUYetfRA=";
      finalImageTag = "v0.108.0-b.72";
    };
  };
  bazarr = {
    pname = "bazarr";
    version = "1.5.2";
    src = dockerTools.pullImage {
      imageName = "linuxserver/bazarr";
      imageDigest = "sha256:2458b13b6bdb9beee13acd2c70172140e9f9362488914d9f7cd95a473c3742b7";
      sha256 = "sha256-bL/bWq3sQJJlaFpzi2bpWqZMEQmi7So5OuMszIKQJ/I=";
      finalImageTag = "1.5.2";
    };
  };
  jellyfin = {
    pname = "jellyfin";
    version = "2025072105";
    src = dockerTools.pullImage {
      imageName = "jellyfin/jellyfin";
      imageDigest = "sha256:ba8630eb28cc311729c2a4122efe29d44254afb721a21d4ceb5972d4349bc2ef";
      sha256 = "sha256-nLo6QhNZG5IutINFuTO71QhElSsvZMuBKqZi4e2PuR0=";
      finalImageTag = "2025072105";
    };
  };
  minecraft-server = {
    pname = "minecraft-server";
    version = "java8";
    src = dockerTools.pullImage {
      imageName = "itzg/minecraft-server";
      imageDigest = "sha256:89d061b3953d2ba5852f43dd6818462e8b6ac64887593ec4539782a60f6f8e81";
      sha256 = "sha256-/u+uBMquXRhzufAnqtyq3UeOuwUw7O2uawWF8G4IV2M=";
      finalImageTag = "java8";
    };
  };
  odin = {
    pname = "odin";
    version = "3.1.2";
    src = dockerTools.pullImage {
      imageName = "mbround18/valheim";
      imageDigest = "sha256:44c2ab93f34c63765b0fbab8f5ec5f67a35f315d995760bf8d4af6ba2f766860";
      sha256 = "sha256-hy818wdfk2bnksBulNhrEUZve+gFRNVczBo/Wr6PL+0=";
      finalImageTag = "3.1.2";
    };
  };
  prowlarr = {
    pname = "prowlarr";
    version = "1.37.0";
    src = dockerTools.pullImage {
      imageName = "linuxserver/prowlarr";
      imageDigest = "sha256:68d16fa1a692ec26c4340a23f50b5980899c5630ce881fd0015dac849cbb9b53";
      sha256 = "sha256-AZR4wkNeuW6xn8svbGsLf+olcinHViAZXXc6pUjw324=";
      finalImageTag = "1.37.0";
    };
  };
  qbittorrent = {
    pname = "qbittorrent";
    version = "20.04.1";
    src = dockerTools.pullImage {
      imageName = "linuxserver/qbittorrent";
      imageDigest = "sha256:fc98c8af048936d0070dc5e5992feab08664f8a61a860d91be02f782f8721485";
      sha256 = "sha256-GZAC1cA7pShhKQB92d8JMbsUUYICplel+Mp2GqkFH/w=";
      finalImageTag = "20.04.1";
    };
  };
  radarr = {
    pname = "radarr";
    version = "5.26.2";
    src = dockerTools.pullImage {
      imageName = "linuxserver/radarr";
      imageDigest = "sha256:07a474b61394553e047ad43a1a78c1047fc99be0144c509dd91e3877f402ebcb";
      sha256 = "sha256-/nCMiUF0IegcSST1duJ2Gad8dAh2UWDFrl0qC9UjNSo=";
      finalImageTag = "5.26.2";
    };
  };
  sonarr = {
    pname = "sonarr";
    version = "4.0.15";
    src = dockerTools.pullImage {
      imageName = "linuxserver/sonarr";
      imageDigest = "sha256:1156329d544b38bd1483add75c9b72c559f20e1ca043fd2d6376c2589d38951f";
      sha256 = "sha256-7+ggXjaEzH14UgTzwsOHSRIUKNYJ+oADHklz38ORRCA=";
      finalImageTag = "4.0.15";
    };
  };
  tor-privoxy = {
    pname = "tor-privoxy";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "dockage/tor-privoxy";
      imageDigest = "sha256:7688b62223e1107adcda1418c2f9f95f9173abec7118431d776a0793135844f0";
      sha256 = "sha256-pWk0Ci7gSSfzUaY2bOtOaMlFnBjO0gBtwIU7nuq8ZMQ=";
      finalImageTag = "latest";
    };
  };
}
