# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  adguard = {
    pname = "adguard";
    version = "v0.108.0-b.74";
    src = dockerTools.pullImage {
      imageName = "adguard/adguardhome";
      imageDigest = "sha256:141182e694ae8acb744be6d83ce2f67596da3f7dfd90be66980c219fcaf236bb";
      sha256 = "sha256-OEwah3iT6gE7khlcnH370rL3HVmcJ7PiqwYKN1JUbts=";
      finalImageTag = "v0.108.0-b.74";
    };
  };
  bazarr = {
    pname = "bazarr";
    version = "1.5.2";
    src = dockerTools.pullImage {
      imageName = "linuxserver/bazarr";
      imageDigest = "sha256:f9cb78eaec1d77017f5c3e5b7aa07106fe4433a77fd902d01e91213f7c991499";
      sha256 = "sha256-W+F6PzdFu9H/mkikfbIUkRhfS+8E2jk2dRG7PBdY77c=";
      finalImageTag = "1.5.2";
    };
  };
  jellyfin = {
    pname = "jellyfin";
    version = "2025090105";
    src = dockerTools.pullImage {
      imageName = "jellyfin/jellyfin";
      imageDigest = "sha256:6a558cad78edc505db4b8d30951312d617242f70a53a83076d288ce90672ed4a";
      sha256 = "sha256-bkwzy0zw/JkN+RHLpJT+lF6iwRsM3yZdAJM/ISpqe/A=";
      finalImageTag = "2025090105";
    };
  };
  minecraft-server = {
    pname = "minecraft-server";
    version = "java8";
    src = dockerTools.pullImage {
      imageName = "itzg/minecraft-server";
      imageDigest = "sha256:5684c55191d84a3ff2406c8c559452e79571bfcbb4cb609aabf55925d737260a";
      sha256 = "sha256-dPUAPfk4I0qsN9bh4T2ivQLGeszEdUV9soC2isostxA=";
      finalImageTag = "java8";
    };
  };
  odin = {
    pname = "odin";
    version = "3.3.0";
    src = dockerTools.pullImage {
      imageName = "mbround18/valheim";
      imageDigest = "sha256:99b1f4f90a1ff3cb95b6f4f1701afaa4fba9bed35fd614f88f885f7e647a4536";
      sha256 = "sha256-w/D7yM2qCF0MgliDeFVWI/6MAfbzuT0Y2DOSLrzwQg4=";
      finalImageTag = "3.3.0";
    };
  };
  prowlarr = {
    pname = "prowlarr";
    version = "2.0.5";
    src = dockerTools.pullImage {
      imageName = "linuxserver/prowlarr";
      imageDigest = "sha256:4f2a6d597845b2f3e19284b1d982b3e0b4bd7c22472c2979c956aa198b83f472";
      sha256 = "sha256-09jFUvZpCeNw3u8s+jfvhA3u2nrCK8TVn4VqtdUQX7k=";
      finalImageTag = "2.0.5";
    };
  };
  qbittorrent = {
    pname = "qbittorrent";
    version = "20.04.1";
    src = dockerTools.pullImage {
      imageName = "linuxserver/qbittorrent";
      imageDigest = "sha256:fc98c8af048936d0070dc5e5992feab08664f8a61a860d91be02f782f8721485";
      sha256 = "sha256-GZAC1cA7pShhKQB92d8JMbsUUYICplel+Mp2GqkFH/w=";
      finalImageTag = "20.04.1";
    };
  };
  radarr = {
    pname = "radarr";
    version = "5.26.2";
    src = dockerTools.pullImage {
      imageName = "linuxserver/radarr";
      imageDigest = "sha256:7eb64f5af8bbe48e79bc55c0c37ca8db89b2f073a9ff0094f603916ae1df9de8";
      sha256 = "sha256-HA+OuyjCjgOvH9zQ/RKLCY3A1Ls3VEBM5U1OeF0Ut3I=";
      finalImageTag = "5.26.2";
    };
  };
  sonarr = {
    pname = "sonarr";
    version = "4.0.15";
    src = dockerTools.pullImage {
      imageName = "linuxserver/sonarr";
      imageDigest = "sha256:e00e87e0e7c24fdc992093756f120a6ab292790b6a637ff3641bf813091cd726";
      sha256 = "sha256-4vcNec53fOwPQFsjg9Eii11NDF3Mx+gfA49+jOCRluQ=";
      finalImageTag = "4.0.15";
    };
  };
  tor-privoxy = {
    pname = "tor-privoxy";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "dockage/tor-privoxy";
      imageDigest = "sha256:7688b62223e1107adcda1418c2f9f95f9173abec7118431d776a0793135844f0";
      sha256 = "sha256-pWk0Ci7gSSfzUaY2bOtOaMlFnBjO0gBtwIU7nuq8ZMQ=";
      finalImageTag = "latest";
    };
  };
}
