# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  adguard = {
    pname = "adguard";
    version = "v0.108.0-b.71";
    src = dockerTools.pullImage {
      imageName = "adguard/adguardhome";
      imageDigest = "sha256:3c49b214ca9264f85c488d000cf817eee2795af8e60c9a109f5afc187c01e063";
      sha256 = "sha256-1mB8uA7Bt/H/XPjG1qyiBhkVdEn97s6GMDjfadB7l2w=";
      finalImageTag = "v0.108.0-b.71";
    };
  };
  bazarr = {
    pname = "bazarr";
    version = "1.5.2";
    src = dockerTools.pullImage {
      imageName = "linuxserver/bazarr";
      imageDigest = "sha256:2458b13b6bdb9beee13acd2c70172140e9f9362488914d9f7cd95a473c3742b7";
      sha256 = "sha256-bL/bWq3sQJJlaFpzi2bpWqZMEQmi7So5OuMszIKQJ/I=";
      finalImageTag = "1.5.2";
    };
  };
  jellyfin = {
    pname = "jellyfin";
    version = "2025061605";
    src = dockerTools.pullImage {
      imageName = "jellyfin/jellyfin";
      imageDigest = "sha256:8582d5578dd6ebe527f368a898124cc13deb454cb5dd767559a249ab4b6f76d6";
      sha256 = "sha256-RtLkdaJqiTe4mTwo6N92DzqoHekpemYuCLDYGcj/FW8=";
      finalImageTag = "2025061605";
    };
  };
  minecraft-server = {
    pname = "minecraft-server";
    version = "java8";
    src = dockerTools.pullImage {
      imageName = "itzg/minecraft-server";
      imageDigest = "sha256:89d061b3953d2ba5852f43dd6818462e8b6ac64887593ec4539782a60f6f8e81";
      sha256 = "sha256-/u+uBMquXRhzufAnqtyq3UeOuwUw7O2uawWF8G4IV2M=";
      finalImageTag = "java8";
    };
  };
  odin = {
    pname = "odin";
    version = "3.1.2";
    src = dockerTools.pullImage {
      imageName = "mbround18/valheim";
      imageDigest = "sha256:44c2ab93f34c63765b0fbab8f5ec5f67a35f315d995760bf8d4af6ba2f766860";
      sha256 = "sha256-hy818wdfk2bnksBulNhrEUZve+gFRNVczBo/Wr6PL+0=";
      finalImageTag = "3.1.2";
    };
  };
  prowlarr = {
    pname = "prowlarr";
    version = "1.37.0";
    src = dockerTools.pullImage {
      imageName = "linuxserver/prowlarr";
      imageDigest = "sha256:68d16fa1a692ec26c4340a23f50b5980899c5630ce881fd0015dac849cbb9b53";
      sha256 = "sha256-AZR4wkNeuW6xn8svbGsLf+olcinHViAZXXc6pUjw324=";
      finalImageTag = "1.37.0";
    };
  };
  qbittorrent = {
    pname = "qbittorrent";
    version = "20.04.1";
    src = dockerTools.pullImage {
      imageName = "linuxserver/qbittorrent";
      imageDigest = "sha256:fc98c8af048936d0070dc5e5992feab08664f8a61a860d91be02f782f8721485";
      sha256 = "sha256-GZAC1cA7pShhKQB92d8JMbsUUYICplel+Mp2GqkFH/w=";
      finalImageTag = "20.04.1";
    };
  };
  radarr = {
    pname = "radarr";
    version = "5.26.2";
    src = dockerTools.pullImage {
      imageName = "linuxserver/radarr";
      imageDigest = "sha256:07a474b61394553e047ad43a1a78c1047fc99be0144c509dd91e3877f402ebcb";
      sha256 = "sha256-/nCMiUF0IegcSST1duJ2Gad8dAh2UWDFrl0qC9UjNSo=";
      finalImageTag = "5.26.2";
    };
  };
  sonarr = {
    pname = "sonarr";
    version = "4.0.14";
    src = dockerTools.pullImage {
      imageName = "linuxserver/sonarr";
      imageDigest = "sha256:cdf5eb3cfa207d46b066bfbb41b03576c67a1f6ecc8aba19146d0f7349ec79dc";
      sha256 = "sha256-RvBpfZrU4J9vCHByxKxOzqef+J3WXk+LzEM9wRh0o3o=";
      finalImageTag = "4.0.14";
    };
  };
  tor-privoxy = {
    pname = "tor-privoxy";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "dockage/tor-privoxy";
      imageDigest = "sha256:7688b62223e1107adcda1418c2f9f95f9173abec7118431d776a0793135844f0";
      sha256 = "sha256-pWk0Ci7gSSfzUaY2bOtOaMlFnBjO0gBtwIU7nuq8ZMQ=";
      finalImageTag = "latest";
    };
  };
}
