# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  # NOTE: `/`, `/nix` and `/boot` are declared by disko.nix (two-SSD btrfs pool).
  # Do not re-add them here or they will conflict with the disko-generated mounts.

  fileSystems."/mnt/amirani" = {
    device = "/dev/disk/by-uuid/fc155353-2c26-40f4-992a-204b174c270c";
    fsType = "ext4";
    options = [
      "users"
      "nofail"
    ];
  };
  fileSystems."/mnt/titan" = {
    device = "/dev/disk/by-uuid/37eaa6ae-251c-49b4-afc4-5824c26b0cde";
    fsType = "ext4";
    options = [
      "users"
      "nofail"
    ];
  };
  fileSystems."/mnt/phoebe" = {
    device = "/dev/disk/by-uuid/e383424c-bcda-4e10-bdcf-522feb8b7949";
    fsType = "ext4";
    options = [
      "users"
      "nofail"
    ];
  };

  environment.systemPackages = with pkgs; [
    mergerfs
  ];

  fileSystems."/external_storage" = {
    fsType = "fuse.mergerfs";
    device = "/mnt/amirani:/mnt/titan:/mnt/phoebe";
    options = [
      "cache.files=partial"
      "dropcacheonclose=true"
      "category.create=mfs"
      "fsname=/dev/mergerfs/external_storage"
      "nofail"
    ];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
