name: Build & Cache

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: saturn
            runner: ubuntu-latest
          - host: mars
            runner: ubuntu-latest
          - host: luna
            runner: ubuntu-latest
          - host: eros
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.host }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: cramt
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build ${{ matrix.host }}
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --print-build-logs
